alias: Flux - Start Force Export on Inverters
description: ""
trigger:
  - platform: time
    at: "16:00:00"
condition:
    - condition: numeric_state
      entity_id: sensor.givtcp_<serial number>_soc
      # input.number.force_export_start_percentage is a helper and can be created under settings -> Integrations -> Helpers -> # Add new Helper -> Number.
      # Create it and then add it to your dashboard so that you can control it.
      above: input_number.force_export_start_percentage
action:
  - service: input_number.set_value
    target:
      entity_id: input_number.force_export_current_duration
    data:
      value: 60
mode: restart